# Note:
# Llama-3.2-1B officially supports English (en), German (de), French (fr), Italian (it), Portuguese (pt), Hindi (hi), Spanish (es), and Thai (th)
# Additionally, add Bulgarian (bg), Russian (ru), Turkish (tr), and Vietnamese (vi) because they have accuracy above 40% on the XNLI task based on `llama3.2_eval.ipynb`
# Add Japanese (ja), Korean (ko), and Chinese (zh) for PAWS-X task
lang_choices = [
    "en",
    "de",
    "fr",
    "it",
    "pt",
    "hi",
    "es",
    "th",
    "bg",
    "ru",
    "tr",
    "vi",
    "ja",
    "ko",
    "zh",
]

flore_plus_lang_choices = [
    "eng_Latn",
    "deu_Latn",
    "fra_Latn",
    "ita_Latn",
    "por_Latn",
    "hin_Deva",
    "spa_Latn",
    "tha_Thai",
    "bul_Cyrl",
    "rus_Cyrl",
    "tur_Latn",
    "vie_Latn",
    "jpn_Jpan",
    "kor_Hang",
    "cmn_Hans",
]

iso639_2_lang_choices = [
    "eng",
    "deu",
    "fra",
    "ita",
    "por",
    "hin",
    "spa",
    "tha",
    "bul",
    "rus",
    "tur",
    "vie",
    "jpn",
    "kor",
    "zho",
]

lang_choices = [
    *lang_choices,
    *flore_plus_lang_choices,
    *iso639_2_lang_choices,
]

lang_choices_to_qualified_name = {
    "en": "English",
    "de": "German",
    "fr": "French",
    "it": "Italian",
    "pt": "Portuguese",
    "hi": "Hindi",
    "es": "Spanish",
    "th": "Thai",
    "bg": "Bulgarian",
    "ru": "Russian",
    "tr": "Turkish",
    "vi": "Vietnamese",
    "ja": "Japanese",
    "ko": "Korean",
    "zh": "Chinese",
    "eng_Latn": "English",
    "deu_Latn": "German",
    "fra_Latn": "French",
    "ita_Latn": "Italian",
    "por_Latn": "Portuguese",
    "hin_Deva": "Hindi",
    "spa_Latn": "Spanish",
    "tha_Thai": "Thai",
    "bul_Cyrl": "Bulgarian",
    "rus_Cyrl": "Russian",
    "tur_Latn": "Turkish",
    "vie_Latn": "Vietnamese",
    "jpn_Jpan": "Japanese",
    "kor_Hang": "Korean",
    "cmn_Hans": "Chinese",
    "eng": "English",
    "deu": "German",
    "fra": "French",
    "ita": "Italian",
    "por": "Portuguese",
    "hin": "Hindi",
    "spa": "Spanish",
    "tha": "Thai",
    "bul": "Bulgarian",
    "rus": "Russian",
    "tur": "Turkish",
    "vie": "Vietnamese",
    "jpn": "Japanese",
    "kor": "Korean",
    "cmn": "Chinese",
}

lang_choices_to_iso639_1 = {
    "en": "en",
    "de": "de",
    "fr": "fr",
    "it": "it",
    "pt": "pt",
    "hi": "hi",
    "es": "es",
    "th": "th",
    "bg": "bg",
    "ru": "ru",
    "tr": "tr",
    "vi": "vi",
    "ja": "ja",
    "ko": "ko",
    "zh": "zh",
    "eng_Latn": "en",
    "deu_Latn": "de",
    "fra_Latn": "fr",
    "ita_Latn": "it",
    "por_Latn": "pt",
    "hin_Deva": "hi",
    "spa_Latn": "es",
    "tha_Thai": "th",
    "bul_Cyrl": "bg",
    "rus_Cyrl": "ru",
    "tur_Latn": "tr",
    "vie_Latn": "vi",
    "jpn_Jpan": "ja",
    "kor_Hang": "ko",
    "cmn_Hans": "zh",
    "eng": "en",
    "deu": "de",
    "fra": "fr",
    "ita": "it",
    "por": "pt",
    "hin": "hi",
    "spa": "es",
    "tha": "th",
    "bul": "bg",
    "rus": "ru",
    "tur": "tr",
    "vie": "vi",
    "jpn": "ja",
    "kor": "ko",
    "cmn": "zh",
    "zho": "zh",
    "English": "en",
    "German": "de",
    "French": "fr",
    "Italian": "it",
    "Portuguese": "pt",
    "Hindi": "hi",
    "Spanish": "es",
    "Thai": "th",
    "Bulgarian": "bg",
    "Russian": "ru",
    "Turkish": "tr",
    "Vietnamese": "vi",
    "Japanese": "ja",
    "Korean": "ko",
    "Chinese": "zh",
}

lang_choices_to_iso639_2 = {
    "en": "eng",
    "de": "deu",
    "fr": "fra",
    "it": "ita",
    "pt": "por",
    "hi": "hin",
    "es": "spa",
    "th": "tha",
    "bg": "bul",
    "ru": "rus",
    "tr": "tur",
    "vi": "vie",
    "ja": "jpn",
    "ko": "kor",
    "zh": "zho",
    "eng_Latn": "eng",
    "deu_Latn": "deu",
    "fra_Latn": "fra",
    "ita_Latn": "ita",
    "por_Latn": "por",
    "hin_Deva": "hin",
    "spa_Latn": "spa",
    "tha_Thai": "tha",
    "bul_Cyrl": "bul",
    "rus_Cyrl": "rus",
    "tur_Latn": "tur",
    "vie_Latn": "vie",
    "jpn_Jpan": "jpn",
    "kor_Hang": "kor",
    "cmn_Hans": "zho",
    "eng": "eng",
    "deu": "deu",
    "fra": "fra",
    "ita": "ita",
    "por": "por",
    "hin": "hin",
    "spa": "spa",
    "tha": "tha",
    "bul": "bul",
    "rus": "rus",
    "tur": "tur",
    "vie": "vie",
    "jpn": "jpn",
    "kor": "kor",
    "cmn": "zho",
    "English": "eng",
    "German": "deu",
    "French": "fra",
    "Italian": "ita",
    "Portuguese": "por",
    "Hindi": "hin",
    "Spanish": "spa",
    "Thai": "tha",
    "Bulgarian": "bul",
    "Russian": "rus",
    "Turkish": "tur",
    "Vietnamese": "vie",
    "Japanese": "jpn",
    "Korean": "kor",
    "Chinese": "zho",
}

lang_choices_to_flores = {
    "en": "eng_Latn",
    "de": "deu_Latn",
    "fr": "fra_Latn",
    "it": "ita_Latn",
    "pt": "por_Latn",
    "hi": "hin_Deva",
    "es": "spa_Latn",
    "th": "tha_Thai",
    "bg": "bul_Cyrl",
    "ru": "rus_Cyrl",
    "tr": "tur_Latn",
    "vi": "vie_Latn",
    "ja": "jpn_Jpan",
    "ko": "kor_Hang",
    "zh": "cmn_Hans",
    "eng_Latn": "eng_Latn",
    "deu_Latn": "deu_Latn",
    "fra_Latn": "fra_Latn",
    "ita_Latn": "ita_Latn",
    "por_Latn": "por_Latn",
    "hin_Deva": "hin_Deva",
    "spa_Latn": "spa_Latn",
    "tha_Thai": "tha_Thai",
    "bul_Cyrl": "bul_Cyrl",
    "rus_Cyrl": "rus_Cyrl",
    "tur_Latn": "tur_Latn",
    "vie_Latn": "vie_Latn",
    "jpn_Jpan": "jpn_Jpan",
    "kor_Hang": "kor_Hang",
    "cmn_Hans": "cmn_Hans",
    "eng": "eng_Latn",
    "deu": "deu_Latn",
    "fra": "fra_Latn",
    "ita": "ita_Latn",
    "por": "por_Latn",
    "hin": "hin_Deva",
    "spa": "spa_Latn",
    "tha": "tha_Thai",
    "bul": "bul_Cyrl",
    "rus": "rus_Cyrl",
    "tur": "tur_Latn",
    "vie": "vie_Latn",
    "jpn": "jpn_Jpan",
    "kor": "kor_Hang",
    "cmn": "cmn_Hans",
    "English": "eng_Latn",
    "German": "deu_Latn",
    "French": "fra_Latn",
    "Italian": "ita_Latn",
    "Portuguese": "por_Latn",
    "Hindi": "hin_Deva",
    "Spanish": "spa_Latn",
    "Thai": "tha_Thai",
    "Bulgarian": "bul_Cyrl",
    "Russian": "rus_Cyrl",
    "Turkish": "tur_Latn",
    "Vietnamese": "vie_Latn",
    "Japanese": "jpn_Jpan",
    "Korean": "kor_Hang",
    "Chinese": "cmn_Hans",
}

language_colors = {
    "bg": "#fd3216",
    "zh": "#00fe35",
    "en": "#6a76fc",
    "fr": "#fed4c4",
    "de": "#fe00ce",
    "hi": "#0df9ff",
    "it": "#f6f926",
    "jp": "#ff9616",
    "ko": "#479b55",
    "pt": "#eea6fb",
    "ru": "#dc587d",
    "es": "#d626ff",
    "th": "#6e899c",
    "tr": "#00b5f7",
    "vi": "#b68e00",
}

model_choices = [
    "meta-llama/Llama-3.2-1B",
    "meta-llama/Llama-3.1-8B",
    "google/gemma-2-2b",
    "google/gemma-2-9b",
]

dataset_choices = [
    "facebook/xnli",
    "google-research-datasets/paws-x",
    "openlanguagedata/flores_plus",
    "MartinThoma/wili_2018",
]

prompt_templates = {
    "facebook/xnli": {
        "en": "{premise} {hypothesis}",
        "de": "{premise} {hypothesis}",
        "fr": "{premise} {hypothesis}",
        "hi": "{premise} {hypothesis}",
        "es": "{premise} {hypothesis}",
        "th": "{premise} {hypothesis}",
        "bg": "{premise} {hypothesis}",
        "ru": "{premise} {hypothesis}",
        "tr": "{premise} {hypothesis}",
        "vi": "{premise} {hypothesis}",
    },
    "google-research-datasets/paws-x": {
        "en": "{sentence1}",
        "de": "{sentence1}",
        "fr": "{sentence1}",
        "es": "{sentence1}",
        "ja": "{sentence1}",
        "ko": "{sentence1}",
        "zh": "{sentence1}",
    },
    "openlanguagedata/flores_plus": {
        "eng_Latn": "{text}",
        "deu_Latn": "{text}",
        "fra_Latn": "{text}",
        "ita_Latn": "{text}",
        "por_Latn": "{text}",
        "hin_Deva": "{text}",
        "spa_Latn": "{text}",
        "tha_Thai": "{text}",
        "bul_Cyrl": "{text}",
        "rus_Cyrl": "{text}",
        "tur_Latn": "{text}",
        "vie_Latn": "{text}",
        "jpn_Jpan": "{text}",
        "kor_Hang": "{text}",
        "cmn_Hans": "{text}",
    },
    "MartinThoma/wili_2018": {
        "eng": "{sentence}",
        "deu": "{sentence}",
        "fra": "{sentence}",
        "ita": "{sentence}",
        "por": "{sentence}",
        "hin": "{sentence}",
        "spa": "{sentence}",
        "tha": "{sentence}",
        "bul": "{sentence}",
        "rus": "{sentence}",
        "tur": "{sentence}",
        "vie": "{sentence}",
        "jpn": "{sentence}",
        "kor": "{sentence}",
        "zho": "{sentence}",
    },
}

sae_model_choices = [
    "EleutherAI/sae-Llama-3.2-1B-131k",
    "EleutherAI/sae",  # Local SAE
    "llama_scope_lxm_32x",
    "gemma-scope-2b-pt-mlp-canonical",
    "gemma-scope-9b-pt-mlp-canonical",
]

sae_model_layer_to_hookpoint = {
    # Sparsify SAE models
    "meta-llama/Llama-3.2-1B": {
        "EleutherAI/sae-Llama-3.2-1B-131k": {
            "model.layers.0.mlp": "layers.0.mlp",
            "model.layers.1.mlp": "layers.1.mlp",
            "model.layers.2.mlp": "layers.2.mlp",
            "model.layers.3.mlp": "layers.3.mlp",
            "model.layers.4.mlp": "layers.4.mlp",
            "model.layers.5.mlp": "layers.5.mlp",
            "model.layers.6.mlp": "layers.6.mlp",
            "model.layers.7.mlp": "layers.7.mlp",
            "model.layers.8.mlp": "layers.8.mlp",
            "model.layers.9.mlp": "layers.9.mlp",
            "model.layers.10.mlp": "layers.10.mlp",
            "model.layers.11.mlp": "layers.11.mlp",
            "model.layers.12.mlp": "layers.12.mlp",
            "model.layers.13.mlp": "layers.13.mlp",
            "model.layers.14.mlp": "layers.14.mlp",
            "model.layers.15.mlp": "layers.15.mlp",
        },
        # Custom SAE model for Llama-3.2-1B
        "EleutherAI/sae": {
            "model.layers.0.mlp": "layers.0.mlp",
            "model.layers.1.mlp": "layers.1.mlp",
            "model.layers.2.mlp": "layers.2.mlp",
            "model.layers.3.mlp": "layers.3.mlp",
            "model.layers.4.mlp": "layers.4.mlp",
            "model.layers.5.mlp": "layers.5.mlp",
            "model.layers.6.mlp": "layers.6.mlp",
            "model.layers.7.mlp": "layers.7.mlp",
            "model.layers.8.mlp": "layers.8.mlp",
            "model.layers.9.mlp": "layers.9.mlp",
            "model.layers.10.mlp": "layers.10.mlp",
            "model.layers.11.mlp": "layers.11.mlp",
            "model.layers.12.mlp": "layers.12.mlp",
            "model.layers.13.mlp": "layers.13.mlp",
            "model.layers.14.mlp": "layers.14.mlp",
            "model.layers.15.mlp": "layers.15.mlp",
        },
    },
    # SAE Lens models
    "meta-llama/Llama-3.1-8B": {
        "llama_scope_lxm_32x": {
            "model.layers.0.mlp": "l0m_32x",
            "model.layers.1.mlp": "l1m_32x",
            "model.layers.2.mlp": "l2m_32x",
            "model.layers.3.mlp": "l3m_32x",
            "model.layers.4.mlp": "l4m_32x",
            "model.layers.5.mlp": "l5m_32x",
            "model.layers.6.mlp": "l6m_32x",
            "model.layers.7.mlp": "l7m_32x",
            "model.layers.8.mlp": "l8m_32x",
            "model.layers.9.mlp": "l9m_32x",
            "model.layers.10.mlp": "l10m_32x",
            "model.layers.11.mlp": "l11m_32x",
            "model.layers.12.mlp": "l12m_32x",
            "model.layers.13.mlp": "l13m_32x",
            "model.layers.14.mlp": "l14m_32x",
            "model.layers.15.mlp": "l15m_32x",
            "model.layers.16.mlp": "l16m_32x",
            "model.layers.17.mlp": "l17m_32x",
            "model.layers.18.mlp": "l18m_32x",
            "model.layers.19.mlp": "l19m_32x",
            "model.layers.20.mlp": "l20m_32x",
            "model.layers.21.mlp": "l21m_32x",
            "model.layers.22.mlp": "l22m_32x",
            "model.layers.23.mlp": "l23m_32x",
            "model.layers.24.mlp": "l24m_32x",
            "model.layers.25.mlp": "l25m_32x",
            "model.layers.26.mlp": "l26m_32x",
            "model.layers.27.mlp": "l27m_32x",
            "model.layers.28.mlp": "l28m_32x",
            "model.layers.29.mlp": "l29m_32x",
            "model.layers.30.mlp": "l30m_32x",
            "model.layers.31.mlp": "l31m_32x",
        },
    },
    "google/gemma-2-2b": {
        "gemma-scope-2b-pt-mlp-canonical": {
            "model.layers.0.post_feedforward_layernorm": "layer_0/width_65k/canonical",
            "model.layers.1.post_feedforward_layernorm": "layer_1/width_65k/canonical",
            "model.layers.2.post_feedforward_layernorm": "layer_2/width_65k/canonical",
            "model.layers.3.post_feedforward_layernorm": "layer_3/width_65k/canonical",
            "model.layers.4.post_feedforward_layernorm": "layer_4/width_65k/canonical",
            "model.layers.5.post_feedforward_layernorm": "layer_5/width_65k/canonical",
            "model.layers.6.post_feedforward_layernorm": "layer_6/width_65k/canonical",
            "model.layers.7.post_feedforward_layernorm": "layer_7/width_65k/canonical",
            "model.layers.8.post_feedforward_layernorm": "layer_8/width_65k/canonical",
            "model.layers.9.post_feedforward_layernorm": "layer_9/width_65k/canonical",
            "model.layers.10.post_feedforward_layernorm": "layer_10/width_65k/canonical",
            "model.layers.11.post_feedforward_layernorm": "layer_11/width_65k/canonical",
            "model.layers.12.post_feedforward_layernorm": "layer_12/width_65k/canonical",
            "model.layers.13.post_feedforward_layernorm": "layer_13/width_65k/canonical",
            "model.layers.14.post_feedforward_layernorm": "layer_14/width_65k/canonical",
            "model.layers.15.post_feedforward_layernorm": "layer_15/width_65k/canonical",
            "model.layers.16.post_feedforward_layernorm": "layer_16/width_65k/canonical",
            "model.layers.17.post_feedforward_layernorm": "layer_17/width_65k/canonical",
            "model.layers.18.post_feedforward_layernorm": "layer_18/width_65k/canonical",
            "model.layers.19.post_feedforward_layernorm": "layer_19/width_65k/canonical",
            "model.layers.20.post_feedforward_layernorm": "layer_20/width_65k/canonical",
            "model.layers.21.post_feedforward_layernorm": "layer_21/width_65k/canonical",
            "model.layers.22.post_feedforward_layernorm": "layer_22/width_65k/canonical",
            "model.layers.23.post_feedforward_layernorm": "layer_23/width_65k/canonical",
            "model.layers.24.post_feedforward_layernorm": "layer_24/width_65k/canonical",
            "model.layers.25.post_feedforward_layernorm": "layer_25/width_65k/canonical",
        }
    },
    "google/gemma-2-9b": {
        "gemma-scope-9b-pt-mlp-canonical": {
            "model.layers.0.post_feedforward_layernorm": "layer_0/width_131k/canonical",
            "model.layers.1.post_feedforward_layernorm": "layer_1/width_131k/canonical",
            "model.layers.2.post_feedforward_layernorm": "layer_2/width_131k/canonical",
            "model.layers.3.post_feedforward_layernorm": "layer_3/width_131k/canonical",
            "model.layers.4.post_feedforward_layernorm": "layer_4/width_131k/canonical",
            "model.layers.5.post_feedforward_layernorm": "layer_5/width_131k/canonical",
            "model.layers.6.post_feedforward_layernorm": "layer_6/width_131k/canonical",
            "model.layers.7.post_feedforward_layernorm": "layer_7/width_131k/canonical",
            "model.layers.8.post_feedforward_layernorm": "layer_8/width_131k/canonical",
            "model.layers.9.post_feedforward_layernorm": "layer_9/width_131k/canonical",
            "model.layers.10.post_feedforward_layernorm": "layer_10/width_131k/canonical",
            "model.layers.11.post_feedforward_layernorm": "layer_11/width_131k/canonical",
            "model.layers.12.post_feedforward_layernorm": "layer_12/width_131k/canonical",
            "model.layers.13.post_feedforward_layernorm": "layer_13/width_131k/canonical",
            "model.layers.14.post_feedforward_layernorm": "layer_14/width_131k/canonical",
            "model.layers.15.post_feedforward_layernorm": "layer_15/width_131k/canonical",
            "model.layers.16.post_feedforward_layernorm": "layer_16/width_131k/canonical",
            "model.layers.17.post_feedforward_layernorm": "layer_17/width_131k/canonical",
            "model.layers.18.post_feedforward_layernorm": "layer_18/width_131k/canonical",
            "model.layers.19.post_feedforward_layernorm": "layer_19/width_131k/canonical",
            "model.layers.20.post_feedforward_layernorm": "layer_20/width_131k/canonical",
            "model.layers.21.post_feedforward_layernorm": "layer_21/width_131k/canonical",
            "model.layers.22.post_feedforward_layernorm": "layer_22/width_131k/canonical",
            "model.layers.23.post_feedforward_layernorm": "layer_23/width_131k/canonical",
            "model.layers.24.post_feedforward_layernorm": "layer_24/width_131k/canonical",
            "model.layers.25.post_feedforward_layernorm": "layer_25/width_131k/canonical",
            "model.layers.26.post_feedforward_layernorm": "layer_26/width_131k/canonical",
            "model.layers.27.post_feedforward_layernorm": "layer_27/width_131k/canonical",
            "model.layers.28.post_feedforward_layernorm": "layer_28/width_131k/canonical",
            "model.layers.29.post_feedforward_layernorm": "layer_29/width_131k/canonical",
            "model.layers.30.post_feedforward_layernorm": "layer_30/width_131k/canonical",
            "model.layers.31.post_feedforward_layernorm": "layer_31/width_131k/canonical",
            "model.layers.32.post_feedforward_layernorm": "layer_32/width_131k/canonical",
            "model.layers.33.post_feedforward_layernorm": "layer_33/width_131k/canonical",
            "model.layers.34.post_feedforward_layernorm": "layer_34/width_131k/canonical",
            "model.layers.35.post_feedforward_layernorm": "layer_35/width_131k/canonical",
            "model.layers.36.post_feedforward_layernorm": "layer_36/width_131k/canonical",
            "model.layers.37.post_feedforward_layernorm": "layer_37/width_131k/canonical",
            "model.layers.38.post_feedforward_layernorm": "layer_38/width_131k/canonical",
            "model.layers.39.post_feedforward_layernorm": "layer_39/width_131k/canonical",
            "model.layers.40.post_feedforward_layernorm": "layer_40/width_131k/canonical",
            "model.layers.41.post_feedforward_layernorm": "layer_41/width_131k/canonical",
        }
    },
}

hookpoint_to_layer = {
    "layers.0.mlp": 0,
    "layers.1.mlp": 1,
    "layers.2.mlp": 2,
    "layers.3.mlp": 3,
    "layers.4.mlp": 4,
    "layers.5.mlp": 5,
    "layers.6.mlp": 6,
    "layers.7.mlp": 7,
    "layers.8.mlp": 8,
    "layers.9.mlp": 9,
    "layers.10.mlp": 10,
    "layers.11.mlp": 11,
    "layers.12.mlp": 12,
    "layers.13.mlp": 13,
    "layers.14.mlp": 14,
    "layers.15.mlp": 15,
    "l0m_32x": 0,
    "l1m_32x": 1,
    "l2m_32x": 2,
    "l3m_32x": 3,
    "l4m_32x": 4,
    "l5m_32x": 5,
    "l6m_32x": 6,
    "l7m_32x": 7,
    "l8m_32x": 8,
    "l9m_32x": 9,
    "l10m_32x": 10,
    "l11m_32x": 11,
    "l12m_32x": 12,
    "l13m_32x": 13,
    "l14m_32x": 14,
    "l15m_32x": 15,
    "l16m_32x": 16,
    "l17m_32x": 17,
    "l18m_32x": 18,
    "l19m_32x": 19,
    "l20m_32x": 20,
    "l21m_32x": 21,
    "l22m_32x": 22,
    "l23m_32x": 23,
    "l24m_32x": 24,
    "l25m_32x": 25,
    "l26m_32x": 26,
    "l27m_32x": 27,
    "l28m_32x": 28,
    "l29m_32x": 29,
    "l30m_32x": 30,
    "l31m_32x": 31,
    "layer_0/width_65k/canonical": 0,
    "layer_1/width_65k/canonical": 1,
    "layer_2/width_65k/canonical": 2,
    "layer_3/width_65k/canonical": 3,
    "layer_4/width_65k/canonical": 4,
    "layer_5/width_65k/canonical": 5,
    "layer_6/width_65k/canonical": 6,
    "layer_7/width_65k/canonical": 7,
    "layer_8/width_65k/canonical": 8,
    "layer_9/width_65k/canonical": 9,
    "layer_10/width_65k/canonical": 10,
    "layer_11/width_65k/canonical": 11,
    "layer_12/width_65k/canonical": 12,
    "layer_13/width_65k/canonical": 13,
    "layer_14/width_65k/canonical": 14,
    "layer_15/width_65k/canonical": 15,
    "layer_16/width_65k/canonical": 16,
    "layer_17/width_65k/canonical": 17,
    "layer_18/width_65k/canonical": 18,
    "layer_19/width_65k/canonical": 19,
    "layer_20/width_65k/canonical": 20,
    "layer_21/width_65k/canonical": 21,
    "layer_22/width_65k/canonical": 22,
    "layer_23/width_65k/canonical": 23,
    "layer_24/width_65k/canonical": 24,
    "layer_25/width_65k/canonical": 25,
    "layer_0/width_131k/canonical": 0,
    "layer_1/width_131k/canonical": 1,
    "layer_2/width_131k/canonical": 2,
    "layer_3/width_131k/canonical": 3,
    "layer_4/width_131k/canonical": 4,
    "layer_5/width_131k/canonical": 5,
    "layer_6/width_131k/canonical": 6,
    "layer_7/width_131k/canonical": 7,
    "layer_8/width_131k/canonical": 8,
    "layer_9/width_131k/canonical": 9,
    "layer_10/width_131k/canonical": 10,
    "layer_11/width_131k/canonical": 11,
    "layer_12/width_131k/canonical": 12,
    "layer_13/width_131k/canonical": 13,
    "layer_14/width_131k/canonical": 14,
    "layer_15/width_131k/canonical": 15,
    "layer_16/width_131k/canonical": 16,
    "layer_17/width_131k/canonical": 17,
    "layer_18/width_131k/canonical": 18,
    "layer_19/width_131k/canonical": 19,
    "layer_20/width_131k/canonical": 20,
    "layer_21/width_131k/canonical": 21,
    "layer_22/width_131k/canonical": 22,
    "layer_23/width_131k/canonical": 23,
    "layer_24/width_131k/canonical": 24,
    "layer_25/width_131k/canonical": 25,
    "layer_26/width_131k/canonical": 26,
    "layer_27/width_131k/canonical": 27,
    "layer_28/width_131k/canonical": 28,
    "layer_29/width_131k/canonical": 29,
    "layer_30/width_131k/canonical": 30,
    "layer_31/width_131k/canonical": 31,
    "layer_32/width_131k/canonical": 32,
    "layer_33/width_131k/canonical": 33,
    "layer_34/width_131k/canonical": 34,
    "layer_35/width_131k/canonical": 35,
    "layer_36/width_131k/canonical": 36,
    "layer_37/width_131k/canonical": 37,
    "layer_38/width_131k/canonical": 38,
    "layer_39/width_131k/canonical": 39,
    "layer_40/width_131k/canonical": 40,
    "layer_41/width_131k/canonical": 41,
}

mlp_to_index = {
    "model.layers.0.mlp": 0,
    "model.layers.1.mlp": 1,
    "model.layers.2.mlp": 2,
    "model.layers.3.mlp": 3,
    "model.layers.4.mlp": 4,
    "model.layers.5.mlp": 5,
    "model.layers.6.mlp": 6,
    "model.layers.7.mlp": 7,
    "model.layers.8.mlp": 8,
    "model.layers.9.mlp": 9,
    "model.layers.10.mlp": 10,
    "model.layers.11.mlp": 11,
    "model.layers.12.mlp": 12,
    "model.layers.13.mlp": 13,
    "model.layers.14.mlp": 14,
    "model.layers.15.mlp": 15,
    "model.layers.16.mlp": 16,
    "model.layers.17.mlp": 17,
    "model.layers.18.mlp": 18,
    "model.layers.19.mlp": 19,
    "model.layers.20.mlp": 20,
    "model.layers.21.mlp": 21,
    "model.layers.22.mlp": 22,
    "model.layers.23.mlp": 23,
    "model.layers.24.mlp": 24,
    "model.layers.25.mlp": 25,
    "model.layers.26.mlp": 26,
    "model.layers.27.mlp": 27,
    "model.layers.28.mlp": 28,
    "model.layers.29.mlp": 29,
    "model.layers.30.mlp": 30,
    "model.layers.31.mlp": 31,
    "model.layers.32.mlp": 32,
    "model.layers.33.mlp": 33,
    "model.layers.34.mlp": 34,
    "model.layers.35.mlp": 35,
    "model.layers.36.mlp": 36,
    "model.layers.37.mlp": 37,
    "model.layers.38.mlp": 38,
    "model.layers.39.mlp": 39,
    "model.layers.40.mlp": 40,
    "model.layers.41.mlp": 41,
    "model.layers.0.post_feedforward_layernorm": 0,
    "model.layers.1.post_feedforward_layernorm": 1,
    "model.layers.2.post_feedforward_layernorm": 2,
    "model.layers.3.post_feedforward_layernorm": 3,
    "model.layers.4.post_feedforward_layernorm": 4,
    "model.layers.5.post_feedforward_layernorm": 5,
    "model.layers.6.post_feedforward_layernorm": 6,
    "model.layers.7.post_feedforward_layernorm": 7,
    "model.layers.8.post_feedforward_layernorm": 8,
    "model.layers.9.post_feedforward_layernorm": 9,
    "model.layers.10.post_feedforward_layernorm": 10,
    "model.layers.11.post_feedforward_layernorm": 11,
    "model.layers.12.post_feedforward_layernorm": 12,
    "model.layers.13.post_feedforward_layernorm": 13,
    "model.layers.14.post_feedforward_layernorm": 14,
    "model.layers.15.post_feedforward_layernorm": 15,
    "model.layers.16.post_feedforward_layernorm": 16,
    "model.layers.17.post_feedforward_layernorm": 17,
    "model.layers.18.post_feedforward_layernorm": 18,
    "model.layers.19.post_feedforward_layernorm": 19,
    "model.layers.20.post_feedforward_layernorm": 20,
    "model.layers.21.post_feedforward_layernorm": 21,
    "model.layers.22.post_feedforward_layernorm": 22,
    "model.layers.23.post_feedforward_layernorm": 23,
    "model.layers.24.post_feedforward_layernorm": 24,
    "model.layers.25.post_feedforward_layernorm": 25,
    "model.layers.26.post_feedforward_layernorm": 26,
    "model.layers.27.post_feedforward_layernorm": 27,
    "model.layers.28.post_feedforward_layernorm": 28,
    "model.layers.29.post_feedforward_layernorm": 29,
    "model.layers.30.post_feedforward_layernorm": 30,
    "model.layers.31.post_feedforward_layernorm": 31,
    "model.layers.32.post_feedforward_layernorm": 32,
    "model.layers.33.post_feedforward_layernorm": 33,
    "model.layers.34.post_feedforward_layernorm": 34,
    "model.layers.35.post_feedforward_layernorm": 35,
    "model.layers.36.post_feedforward_layernorm": 36,
    "model.layers.37.post_feedforward_layernorm": 37,
    "model.layers.38.post_feedforward_layernorm": 38,
    "model.layers.39.post_feedforward_layernorm": 39,
    "model.layers.40.post_feedforward_layernorm": 40,
    "model.layers.41.post_feedforward_layernorm": 41,
}

mlp_acts_to_index = {
    "model.layers.0.mlp.act_fn": 0,
    "model.layers.1.mlp.act_fn": 1,
    "model.layers.2.mlp.act_fn": 2,
    "model.layers.3.mlp.act_fn": 3,
    "model.layers.4.mlp.act_fn": 4,
    "model.layers.5.mlp.act_fn": 5,
    "model.layers.6.mlp.act_fn": 6,
    "model.layers.7.mlp.act_fn": 7,
    "model.layers.8.mlp.act_fn": 8,
    "model.layers.9.mlp.act_fn": 9,
    "model.layers.10.mlp.act_fn": 10,
    "model.layers.11.mlp.act_fn": 11,
    "model.layers.12.mlp.act_fn": 12,
    "model.layers.13.mlp.act_fn": 13,
    "model.layers.14.mlp.act_fn": 14,
    "model.layers.15.mlp.act_fn": 15,
    "model.layers.16.mlp.act_fn": 16,
    "model.layers.17.mlp.act_fn": 17,
    "model.layers.18.mlp.act_fn": 18,
    "model.layers.19.mlp.act_fn": 19,
    "model.layers.20.mlp.act_fn": 20,
    "model.layers.21.mlp.act_fn": 21,
    "model.layers.22.mlp.act_fn": 22,
    "model.layers.23.mlp.act_fn": 23,
    "model.layers.24.mlp.act_fn": 24,
    "model.layers.25.mlp.act_fn": 25,
    "model.layers.26.mlp.act_fn": 26,
    "model.layers.27.mlp.act_fn": 27,
    "model.layers.28.mlp.act_fn": 28,
    "model.layers.29.mlp.act_fn": 29,
    "model.layers.30.mlp.act_fn": 30,
    "model.layers.31.mlp.act_fn": 31,
    "model.layers.32.mlp.act_fn": 32,
    "model.layers.33.mlp.act_fn": 33,
    "model.layers.34.mlp.act_fn": 34,
    "model.layers.35.mlp.act_fn": 35,
    "model.layers.36.mlp.act_fn": 36,
    "model.layers.37.mlp.act_fn": 37,
    "model.layers.38.mlp.act_fn": 38,
    "model.layers.39.mlp.act_fn": 39,
    "model.layers.40.mlp.act_fn": 40,
    "model.layers.41.mlp.act_fn": 41,
}

layer_to_index = {
    **mlp_to_index,
    **mlp_acts_to_index,
}
